### PR TITLE
feat: removed proxy literals from code

### PR DESCRIPTION
**Pull request by koseward**
feat: re-added status post into the status message

### CODE REVIEW

**Comment by koseward** [comment]
> Changes look good! Will this still work for testing in our local environments? If not, should we push these changes to a branch that is specific to production?

It works on mine. If the proxy is set up correctly it shouldn't be an issue. It should check your route on react, and if not found, will forward to the api. I guess issues would be if there are collisions, which I should check for actually

**Comment by koseward** [comment]
There is actually a collision on the observations so I'll need to make another commit. Perhaps I should just namespace our app rn

**Comment by mcauley-penney** [comment]
> > Changes look good! Will this still work for testing in our local environments? If not, should we push these changes to a branch that is specific to production?
> 
> It works on mine. If the proxy is set up correctly it shouldn't be an issue. It should check your route on react, and if not found, will forward to the api. I guess issues would be if there are collisions, which I should check for actually

For sure! I was in class when I asked that. Now that I'm home, I will also test it out when you give the all clear. 


> There is actually a collision on the observations so I'll need to make another commit. Perhaps I should just namespace our app rn

Good catch!

**Review by mcauley-penney — APPROVED** [review]

**Comment by mcauley-penney** [comment]
After this merge, anyone who has issues with the API not working may need to change the proxy address in `package.json` from `http://localhost:5000/` to `http://127.0.0.1:5000`, with or without the trailing slash. As of right now, the team does not know why.

**Pull request merged**
